my_string="eMobilis"
my_int=67
my_complex=1j
my_bool=True
my_bol2=False
my_list=["cow","milk","sheep"]
my_tuple=("Mangoes","oranges","bananas")
my_set={"nissan","Toyota"}
my_dictionaries={"name"}

print(type(my_string))
print(type(my_int))
print(type(my_complex))
print(type(my_bool))
print(type(my_bol2))
print(type(my_list))
print(type(my_tuple))
print(type(my_set))
print(type(my_dictionaries))